name:               "Eddie A Tejeda"
description:        ""

url:                ""
author:             "eddietejeda"
gravatar_hash:      "491a4a6bc98f587e4d44b18b78055223"
twitter:            "eddietejeda"
email:              "website@eddietejeda.com"
github:             "eddietejeda"
linkedin:           "eddietejeda"
mastodon:           "hachyderm.io/@eddietejeda"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
